name: CI

on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Publish
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ github.ref_name}}
          REPO: ${{ github.repository }}
        run: |
          echo $GH_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          docker build . --file Dockerfile --tag ghcr.io/$REPO:$VERSION
          docker push ghcr.io/$REPO:$VERSION